version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
    groups:
      python-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
    groups:
      frontend-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
