from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import LineChart, Reference

wb = Workbook()

# ── Colour constants ──────────────────────────────────────────────────────────
NAVY    = "1F3864"; NAVY_FG  = "FFFFFF"
MID_BLUE= "2E75B6"; BLUE_FG  = "FFFFFF"
L_BLUE  = "D9E1F2"; L_GREEN  = "E2EFDA"
L_RED   = "FCE4D6"; L_AMBER  = "FFF2CC"
AMBER   = "FFD966"; WHITE    = "FFFFFF"
LGREY   = "F2F2F2"; DGREY    = "595959"
RED_TXT = "C00000"; GRN_TXT  = "375623"
BLU_TXT = "0070C0"; BLK_TXT  = "000000"
WARN_BG = "FFFF00"

def s(): return Side(style="thin", color="BFBFBF")
def ts(): return Side(style="medium", color="1F3864")
TB = Border(left=s(), right=s(), top=s(), bottom=s())
HB = Border(left=ts(), right=ts(), top=ts(), bottom=ts())

def fill(h): return PatternFill("solid", fgColor=h)

def _w(ws, col_widths):
    for col, w in col_widths:
        ws.column_dimensions[get_column_letter(col)].width = w

def sheet_title(ws, text, n=8):
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=n)
    c = ws.cell(row=1, column=1, value=text)
    c.font = Font(name="Calibri", size=14, bold=True, color=NAVY_FG)
    c.fill = fill(NAVY)
    c.alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.row_dimensions[1].height = 22
    ws.row_dimensions[2].height = 6  # spacer

def section_hdr(ws, r, text, n=5, start_col=1):
    ws.merge_cells(start_row=r, start_column=start_col,
                   end_row=r, end_column=start_col+n-1)
    c = ws.cell(row=r, column=start_col, value=text)
    c.font = Font(name="Calibri", size=10, bold=True, color=NAVY_FG)
    c.fill = fill(NAVY)
    c.border = HB
    c.alignment = Alignment(horizontal="left", vertical="center", indent=1)

def col_hdr(ws, r, col, text):
    c = ws.cell(row=r, column=col, value=text)
    c.font = Font(name="Calibri", size=10, bold=True, color=BLUE_FG)
    c.fill = fill(MID_BLUE)
    c.border = TB
    c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

def lbl(ws, r, col, text, bold=False, bg=LGREY, n=1, indent=1):
    if n > 1:
        ws.merge_cells(start_row=r, start_column=col, end_row=r, end_column=col+n-1)
    c = ws.cell(row=r, column=col, value=text)
    c.font = Font(name="Calibri", size=10, bold=bold, color=BLK_TXT)
    c.fill = fill(bg); c.border = TB
    c.alignment = Alignment(horizontal="left", vertical="center", indent=indent)
    return c

def val(ws, r, col, v, fmt=None, bold=False, bg=WHITE, fg=BLK_TXT, center=False):
    c = ws.cell(row=r, column=col, value=v)
    c.font = Font(name="Calibri", size=10, bold=bold, color=fg)
    c.fill = fill(bg); c.border = TB
    if fmt: c.number_format = fmt
    c.alignment = Alignment(horizontal="center" if center else "right",
                            vertical="center")
    return c

def note_cell(ws, r, col, text, bg=WHITE, n=1):
    if n > 1:
        ws.merge_cells(start_row=r, start_column=col, end_row=r, end_column=col+n-1)
    c = ws.cell(row=r, column=col, value=text)
    c.font = Font(name="Calibri", size=9, italic=True, color=DGREY)
    c.fill = fill(bg); c.border = TB
    c.alignment = Alignment(horizontal="left", vertical="center", indent=1, wrap_text=True)
    return c

def footer(ws, r, n=8):
    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=n)
    c = ws.cell(row=r, column=1,
                value="Generated by Alpha Pod pipeline  |  Data: CIQ + yfinance  |  2026-03-08")
    c.font = Font(name="Calibri", size=8, italic=True, color=DGREY)
    c.alignment = Alignment(horizontal="center")


# ══════════════════════════════════════════════════════════════════════════════
# SHEET 1 — Summary
# ══════════════════════════════════════════════════════════════════════════════
ws1 = wb.active
ws1.title = "Summary"
ws1.freeze_panes = "A3"
ws1.sheet_view.showGridLines = False
_w(ws1, [(1,30),(2,16),(3,16),(4,14),(5,20)])

sheet_title(ws1, "IBM  —  DCF Review  |  2026-03-08", 5)

r = 3
section_hdr(ws1, r, "MARKET DATA", 5); r += 1
for label, v in [("Price","$258.85"), ("Market Cap","$242.8B"),
                 ("EV","$293.1B"), ("Revenue (TTM)","$66.8B"),
                 ("Net Debt","$51.0B"), ("Sector","Technology")]:
    bg = LGREY if r % 2 == 1 else WHITE
    lbl(ws1, r, 1, label, bg=bg)
    c = val(ws1, r, 2, v, bg=bg, fg=BLU_TXT, bold=True)
    c.alignment = Alignment(horizontal="right", vertical="center")
    for col in range(3, 6):
        ws1.cell(row=r, column=col).fill = fill(bg)
        ws1.cell(row=r, column=col).border = TB
    r += 1

r += 1
section_hdr(ws1, r, "VALUATION SCENARIOS", 5); r += 1
for h, c in [("Scenario",1),("Probability",2),("Intrinsic Value",3),("vs Price",4),("",5)]:
    col_hdr(ws1, r, c, h)
r += 1

scenarios = [
    ("Bear",              0.20, 126.32, -0.512, L_RED),
    ("Base",              0.60, 227.09, -0.123, L_BLUE),
    ("Bull",              0.20, 474.14,  0.832, L_GREEN),
    ("Expected (prob-wtd)", None, 256.35, -0.001, "BDD7EE"),
]
for name, prob, iv, upside, bg in scenarios:
    bold = name.startswith("Expected")
    fg_up = GRN_TXT if upside >= 0 else RED_TXT
    lbl(ws1, r, 1, name, bold=bold, bg=bg)
    if prob is not None:
        val(ws1, r, 2, prob, "0%", bold=bold, bg=bg, center=True)
    else:
        val(ws1, r, 2, "—", "@", bold=bold, bg=bg, center=True)
    val(ws1, r, 3, iv, "$#,##0.00", bold=bold, bg=bg)
    val(ws1, r, 4, upside, "+0.0%;(0.0%);-", bold=bold, bg=bg, fg=fg_up)
    ws1.cell(row=r, column=5).fill = fill(bg)
    ws1.cell(row=r, column=5).border = TB
    r += 1

r += 1
section_hdr(ws1, r, "CROSS-CHECK METHODS", 5); r += 1
ws1.merge_cells(start_row=r, start_column=1, end_row=r, end_column=2)
for h, c in [("Method",1),("IV / Share",3),("vs Price",4)]:
    col_hdr(ws1, r, c, h)
ws1.cell(row=r, column=5).fill = fill(MID_BLUE)
ws1.cell(row=r, column=5).border = TB
r += 1

xcheck = [
    ("DCF base (blended terminal)",   227.09, -0.123),
    ("  ↳ Gordon Growth component",   280.20,  0.082),
    ("  ↳ Exit Multiple component",   147.43, -0.431),
    ("Economic Profit model",         324.36,  0.253),
    ("FCFE model",                    273.15,  0.055),
    ("Comps — EV/EBITDA",            156.08, -0.397),
    ("Comps — P/E",                  198.15, -0.235),
    ("Analyst consensus target",      321.95,  0.244),
]
for i, (method, iv, upside) in enumerate(xcheck):
    bg = LGREY if i % 2 == 0 else WHITE
    ws1.merge_cells(start_row=r, start_column=1, end_row=r, end_column=2)
    lbl(ws1, r, 1, method, bg=bg)
    val(ws1, r, 3, iv, "$#,##0.00", bg=bg)
    fg = GRN_TXT if upside >= 0 else RED_TXT
    val(ws1, r, 4, upside, "+0.0%;(0.0%);-", bg=bg, fg=fg)
    ws1.cell(row=r, column=5).fill = fill(bg)
    ws1.cell(row=r, column=5).border = TB
    r += 1

r += 1
section_hdr(ws1, r, "REVERSE DCF", 5); r += 1
for label, v, fmt, n in [
    ("Implied growth at market price ($258.85)", 0.081, "0.0%",
     "Source: Alpha Pod reverse DCF binary search"),
    ("Consensus near-term growth (FY1)",          0.066, "0.0%",
     "Source: CIQ consensus estimate (total_revenue_cy_1)"),
    ("Implied premium over consensus",            0.015, "+0.0pp;(0.0pp);-",
     "Market embedding ~150bp outperformance vs consensus"),
]:
    bg = LGREY if r % 2 == 1 else WHITE
    lbl(ws1, r, 1, label, bg=bg)
    val(ws1, r, 2, v, fmt, bold=True, bg=bg, fg=BLU_TXT)
    note_cell(ws1, r, 3, n, bg=bg, n=3)
    r += 1

r += 1
section_hdr(ws1, r, "KEY DIAGNOSTICS", 5); r += 1
diags = [
    ("TV % of EV",        "68.5%", "✓  Below 75% warning threshold",                                WHITE),
    ("DCF – EP gap",      "36.3%", "⚠  Large; driven by margin expansion 12.5%→20% + 15% RONIC",   L_AMBER),
    ("WACC",              "7.06%", "CAPM; β=0.71 relevered, Ke=8.03%; Rf=4.5%, ERP=5.0%",          WHITE),
    ("Beta (relevered)",  "0.71",  "Hamada unlever/relever; self-beta used",                         WHITE),
    ("All health flags",  "PASS",  "TV extreme, growth guardrail, RONIC guardrail: all clear ✓",    L_GREEN),
]
for label, v, n, bg in diags:
    lbl(ws1, r, 1, label, bg=bg)
    c = ws1.cell(row=r, column=2, value=v)
    c.font = Font(name="Calibri", size=10, bold=True)
    c.fill = fill(bg); c.border = TB
    c.alignment = Alignment(horizontal="right", vertical="center")
    note_cell(ws1, r, 3, n, bg=bg, n=3)
    r += 1

r += 2
footer(ws1, r, 5)


# ══════════════════════════════════════════════════════════════════════════════
# SHEET 2 — DCF Assumptions
# ══════════════════════════════════════════════════════════════════════════════
ws2 = wb.create_sheet("DCF Assumptions")
ws2.freeze_panes = "A3"
ws2.sheet_view.showGridLines = False
_w(ws2, [(1,36),(2,13),(3,9),(4,24),(5,44)])

sheet_title(ws2, "IBM  —  DCF Assumptions with Source Lineage  |  2026-03-08", 5)

def assump_hdr_row(ws, r):
    for h, c in [("Driver",1),("Value",2),("Unit",3),("Source",4),("Notes / Audit",5)]:
        col_hdr(ws, r, c, h)

def assump_row(ws, r, driver, v, unit, source, note, bg=WHITE, warn=False):
    lbl(ws, r, 1, driver, bg=bg)
    c = ws.cell(row=r, column=2, value=v)
    c.font = Font(name="Calibri", size=10, bold=True, color=BLU_TXT)
    c.fill = fill(WARN_BG if warn else bg); c.border = TB
    c.alignment = Alignment(horizontal="right", vertical="center")
    for col, text in [(3, unit), (4, source), (5, note)]:
        nc = ws.cell(row=r, column=col, value=text)
        nc.font = Font(name="Calibri", size=9,
                       color=RED_TXT if (warn and col==5) else DGREY)
        nc.fill = fill(WARN_BG if warn else bg); nc.border = TB
        nc.alignment = Alignment(horizontal="left", vertical="center",
                                  indent=1, wrap_text=True)

r = 3
section_hdr(ws2, r, "REVENUE & GROWTH", 5); r += 1
assump_hdr_row(ws2, r); r += 1
for i, (drv, v, u, src, note) in enumerate([
    ("Revenue base",              66799,   "$M",  "CIQ TTM",        "As of 2025-12-31  |  Source: ciq_valuation_snapshot.revenue_mm"),
    ("Near-term growth (Yr 1-5)", "6.6%",  "%",   "ciq_consensus",  "FY1 $71.2B vs TTM $66.8B  |  Source: ciq_comps_snapshot total_revenue_cy_1 (is_target=1)"),
    ("Mid-term growth (Yr 6-10)", "4.6%",  "%",   "derived",        "0.70× fade ratio  |  Technology sector SECTOR_DEFAULTS growth_fade_ratio"),
    ("Terminal growth",           "3.5%",  "%",   "default",        "Technology sector SECTOR_DEFAULTS terminal_growth"),
]):
    assump_row(ws2, r, drv, v, u, src, note, bg=LGREY if i%2==0 else WHITE)
    r += 1

r += 1
section_hdr(ws2, r, "PROFITABILITY", 5); r += 1
assump_hdr_row(ws2, r); r += 1
for i, row in enumerate([
    ("EBIT margin — start",             "12.5%", "%", "CIQ TTM",        "3yr avg operating margin  |  Source: ciq_valuation_snapshot.op_margin_avg_3yr", False),
    ("EBIT margin — target (Yr 10)",    "20.0%", "%", "sector default", "⚠  LARGE STRETCH from 12.5%.  Verify AI/cloud mix-shift thesis before use.", True),
    ("Tax rate — start",                "14.7%", "%", "CIQ",            "Effective tax rate  |  Source: ciq_valuation_snapshot.effective_tax_rate", False),
    ("Tax rate — target",               "15.0%", "%", "company ETR",    "bounded(14.7%, min=15%, max=30%)  |  Company's own rate as convergence target", False),
]):
    drv,v,u,src,note,warn = row
    assump_row(ws2, r, drv, v, u, src, note, bg=LGREY if i%2==0 else WHITE, warn=warn)
    r += 1

r += 1
section_hdr(ws2, r, "CAPITAL STRUCTURE & EXIT", 5); r += 1
assump_hdr_row(ws2, r); r += 1
for i, (drv, v, u, src, note) in enumerate([
    ("Capex % of revenue",   "1.61%",     "%",         "CIQ avg",                   "3yr avg  |  Source: ciq_valuation_snapshot.capex_pct_avg_3yr"),
    ("D&A % of revenue",     "1.13%",     "%",         "CIQ avg",                   "3yr avg  |  Source: ciq_valuation_snapshot.da_pct_avg_3yr"),
    ("Net debt",             "$51,020M",  "$M",        "CIQ",                        "Debt $64,607M less cash $13,587M  |  Source: ciq_valuation_snapshot"),
    ("Exit multiple",        "7.89×",     "EV/EBITDA", "ciq_comps_tev_ebitda_fwd",  "Forward peer median  |  Peers: ORCL ACN HPE MSFT CTSH DXC HON EPAM NTAP"),
    ("WACC",                 "7.06%",     "%",         "yfinance_capm",             "Rf=4.5% ERP=5.0%  |  Source: config/config.yaml wacc_params"),
    ("Shares outstanding",   "948.7M",    "shares",    "CIQ",                       "Source: ciq_valuation_snapshot.shares_out_mm"),
]):
    assump_row(ws2, r, drv, v, u, src, note, bg=LGREY if i%2==0 else WHITE)
    r += 1

r += 1
section_hdr(ws2, r, "WORKING CAPITAL (DSO / DIO / DPO)", 5); r += 1
for h, c in [("Driver",1),("Start",2),("Target (Yr 10)",3),("Source",4),("Notes",5)]:
    col_hdr(ws2, r, c, h)
r += 1
for i, (drv, s, t, src, note) in enumerate([
    ("DSO — Days Sales Outstanding",    "47.0 days","45.6 days","CIQ / 70-30 blend","Baseline CIQ 2024: 42.6d  |  Target = 70%×sector(45d) + 30%×company start"),
    ("DIO — Days Inventory Outstanding","6.7 days", "26.5 days","CIQ / 70-30 blend","⚠  IBM is services-heavy; sector DIO default may overstate target — review"),
    ("DPO — Days Payable Outstanding",  "26.0 days","34.4 days","CIQ / 70-30 blend","Baseline CIQ 2024: 23.7d  |  Target = 70%×sector(38d) + 30%×company start"),
]):
    bg = LGREY if i%2==0 else WHITE
    lbl(ws2, r, 1, drv, bg=bg)
    for col, v in [(2, s), (3, t)]:
        c = ws2.cell(row=r, column=col, value=v)
        c.font = Font(name="Calibri", size=10, bold=True, color=BLU_TXT)
        c.fill = fill(bg); c.border = TB
        c.alignment = Alignment(horizontal="right", vertical="center")
    note_cell(ws2, r, 4, src, bg=bg)
    note_cell(ws2, r, 5, note, bg=bg)
    r += 1

r += 2
footer(ws2, r, 5)


# ══════════════════════════════════════════════════════════════════════════════
# SHEET 3 — QoE Signals
# ══════════════════════════════════════════════════════════════════════════════
ws3 = wb.create_sheet("QoE Signals")
ws3.freeze_panes = "A3"
ws3.sheet_view.showGridLines = False
_w(ws3, [(1,30),(2,12),(3,14),(4,16),(5,14),(6,48)])

sheet_title(ws3, "IBM  —  Quality of Earnings Signals  |  2026-03-08", 6)

r = 3
ws3.merge_cells(start_row=r, start_column=1, end_row=r, end_column=6)
c = ws3.cell(row=r, column=1,
             value="QoE Composite Score:  3 / 5  —  AMBER  |  LLM Layer: NOT RUN (set GEMINI_API_KEY, GOOGLE_API_KEY, or OPENAI_API_KEY to enable)")
c.font = Font(name="Calibri", size=12, bold=True, color="7F4B00")
c.fill = fill(AMBER); c.border = HB
c.alignment = Alignment(horizontal="left", vertical="center", indent=2)
ws3.row_dimensions[r].height = 24
r += 2

section_hdr(ws3, r, "SIGNAL DETAIL", 6); r += 1
for h, c in [("Signal",1),("Score",2),("Value",3),("Thresh — Amber",4),("Thresh — Red",5),("Notes",6)]:
    col_hdr(ws3, r, c, h)
r += 1

signals = [
    ("Sloan Accruals Ratio",         "GREEN", "−3.9%", "8.0%",  "15.0%",
     "Negative = cash earnings exceed accrual earnings. Strong quality signal. Tech sector thresholds applied.",
     L_GREEN, GRN_TXT),
    ("Cash Conversion (CFFO/EBITDA)","GREEN", "105%",  "65%",   "<65%",
     "CFFO well above EBITDA. No working capital drag on cash conversion.",
     L_GREEN, GRN_TXT),
    ("DSO Drift",                    "GREEN", "+4.4d", "5d",    "15d",
     "Current DSO 47.0d vs CIQ 1yr baseline 42.6d. Just below amber threshold. Monitor.",
     L_GREEN, GRN_TXT),
    ("DIO Drift",                    "GREEN", "−0.9d", "5d",    "15d",
     "DIO improving. IBM is largely services/software — DIO naturally low.",
     L_GREEN, GRN_TXT),
    ("DPO Drift",                    "GREEN", "+2.3d", "5d",    "15d",
     "Minor payables stretch vs CIQ 1yr baseline 23.7d. Within normal range.",
     L_GREEN, GRN_TXT),
    ("Capex / D&A Ratio",            "RED",   "0.35×", "0.70×", "<0.70×",
     "⚠  Capex $1.1B vs D&A inflated by acquired intangible amortisation (HashiCorp, Apptio). LLM layer needed to assess 10-K explanation before treating as quality concern.",
     L_RED, RED_TXT),
]
for sig, score, v, amb, red, note, bg, fg in signals:
    lbl(ws3, r, 1, sig, bg=bg)
    sc = ws3.cell(row=r, column=2, value=score)
    sc.font = Font(name="Calibri", size=10, bold=True, color=fg)
    sc.fill = fill(bg); sc.border = TB
    sc.alignment = Alignment(horizontal="center", vertical="center")
    for col, text in [(3,v),(4,amb),(5,red)]:
        c = ws3.cell(row=r, column=col, value=text)
        c.font = Font(name="Calibri", size=10, color=BLK_TXT)
        c.fill = fill(bg); c.border = TB
        c.alignment = Alignment(horizontal="center", vertical="center")
    note_cell(ws3, r, 6, note, bg=bg)
    ws3.row_dimensions[r].height = 30
    r += 1

r += 1
section_hdr(ws3, r, "PM NOTES", 6); r += 1
pm_notes = [
    ("Capex/D&A flag",
     "IBM's capex ($1.1B) falls far below D&A because post-acquisition intangible amortisation inflates D&A — "
     "structurally common for software acquirers. HashiCorp ($6.4B, 2024) and Apptio are the primary drivers. "
     "Run QoEAgent with a configured LLM provider key to verify management 10-K explanation before treating this as a quality concern."),
    ("EBIT normalization",
     "LLM layer NOT run. No EBIT adjustments applied. Reported EBIT used as-is in the DCF. "
     "To enable: set GEMINI_API_KEY, GOOGLE_API_KEY, or OPENAI_API_KEY, then run QoEAgent.analyze('IBM', reported_ebit=<value>)."),
    ("Next steps",
     "If Capex/D&A is confirmed as intangible amortisation artefact: score moves to 4/5 GREEN. "
     "Recommend running full LLM layer and reviewing EBIT margin target (20%) before finalising DCF."),
]
for i, (hdr, note) in enumerate(pm_notes):
    bg = LGREY if i%2==0 else WHITE
    lbl(ws3, r, 1, hdr, bold=True, bg=bg)
    note_cell(ws3, r, 2, note, bg=bg, n=5)
    ws3.row_dimensions[r].height = 45
    r += 1

r += 1
section_hdr(ws3, r, "NWC BASELINE DATA (CIQ HISTORY)", 6); r += 1
for h, c in [("Period",1),("DSO (days)",2),("DIO (days)",3),("DPO (days)",4),("",5),("",6)]:
    col_hdr(ws3, r, c, h)
r += 1
for i, (period, dso, dio, dpo) in enumerate([
    ("2025-12-31 (current)",  47.0, 6.7, 26.0),
    ("2024-12-31 (baseline)", 42.6, 7.6, 23.7),
    ("Drift",                "+4.4","−0.9","+2.3"),
]):
    bg = LGREY if i%2==0 else WHITE
    bold = (i==2)
    lbl(ws3, r, 1, period, bold=bold, bg=bg)
    for col, v in [(2,dso),(3,dio),(4,dpo)]:
        c = ws3.cell(row=r, column=col, value=v)
        c.font = Font(name="Calibri", size=10, bold=bold)
        c.fill = fill(bg); c.border = TB
        c.alignment = Alignment(horizontal="center", vertical="center")
    for col in [5,6]:
        ws3.cell(row=r,column=col).fill = fill(bg)
        ws3.cell(row=r,column=col).border = TB
    r += 1

r += 2
footer(ws3, r, 6)


# ══════════════════════════════════════════════════════════════════════════════
# SHEET 4 — Year-by-Year Forecast
# ══════════════════════════════════════════════════════════════════════════════
ws4 = wb.create_sheet("Year-by-Year Forecast")
ws4.freeze_panes = "B4"
ws4.sheet_view.showGridLines = False
_w(ws4, [(1,26),(2,11),(3,10),(4,11),(5,12),(6,11),(7,11),(8,11),(9,10),(10,14)])

sheet_title(ws4, "IBM  —  Base Case 10-Year Projection  |  2026-03-08", 10)

r = 3
hdrs = ["Driver","Yr 1","Yr 2","Yr 3","Yr 4","Yr 5","Yr 6","Yr 7","Yr 8","Yr 9","Yr 10"]
col_hdr(ws4, r, 1, "Driver")
for i, h in enumerate(hdrs[1:], 2):
    col_hdr(ws4, r, i, h)
r += 1

proj_data = [
    ("Revenue ($B)",    [71.2,75.9,80.9,85.9,91.1,96.3,101.6,106.8,112.0,117.2], "$#,##0.0"),
    ("Revenue growth",  [0.066,0.066,0.066,0.063,0.060,0.057,0.054,0.052,0.049,0.046], "0.0%"),
    ("EBIT ($B)",       [8.9,10.1,11.5,12.9,14.4,16.1,17.8,19.6,21.5,23.4], "$#,##0.0"),
    ("EBIT margin",     [0.125,0.134,0.142,0.150,0.159,0.167,0.175,0.183,0.192,0.200], "0.0%"),
    ("NOPAT ($B)",      [7.6,8.6,9.8,11.0,12.3,13.7,15.1,16.7,18.3,19.9], "$#,##0.0"),
    ("FCFF ($B)",       [6.9,7.7,8.8,9.9,11.2,12.5,13.9,15.4,16.9,18.5], "$#,##0.0"),
    ("PV FCFF ($B)",    [6.5,6.7,7.1,7.5,7.9,8.3,8.6,8.9,9.1,9.4], "$#,##0.0"),
    ("ROIC",            [0.182,0.204,0.226,0.248,0.270,0.293,0.317,0.340,0.362,0.385], "0.0%"),
    ("Inv. Capital ($B)",[42.4,43.4,44.4,45.5,46.6,47.8,49.1,50.4,51.8,53.2], "$#,##0.0"),
]
for i, (drv, values, fmt) in enumerate(proj_data):
    bg = LGREY if i % 2 == 0 else WHITE
    lbl(ws4, r, 1, drv, bg=bg)
    for col, v in enumerate(values, 2):
        c = ws4.cell(row=r, column=col, value=v)
        c.font = Font(name="Calibri", size=10)
        c.fill = fill(bg); c.border = TB
        c.number_format = fmt
        c.alignment = Alignment(horizontal="right", vertical="center")
    r += 1

r += 1
section_hdr(ws4, r, "EV → EQUITY BRIDGE (Base Case)", 4); r += 1
bridge = [
    ("Sum PV of FCFF (Yr 1-10)",          79.7,   "$#,##0.0",  False, WHITE),
    ("PV Terminal Value (blended)",       174.1,   "$#,##0.0",  False, WHITE),
    ("Enterprise Value (operations)",     254.2,   "$#,##0.0",  True,  L_BLUE),
    ("Less: Net Debt",                    -51.0,   "($#,##0.0);$#,##0.0;-", False, WHITE),
    ("Plus: Non-operating assets",         12.3,   "$#,##0.0",  False, WHITE),
    ("Equity Value",                      215.4,   "$#,##0.0",  True,  L_BLUE),
    ("Shares outstanding (M)",            948.7,   "#,##0.0",   False, WHITE),
    ("Intrinsic Value per Share",         227.09,  "$#,##0.00", True,  "BDD7EE"),
]
for label, v, fmt, bold, bg in bridge:
    fg = RED_TXT if v < 0 else BLK_TXT
    lbl(ws4, r, 1, label, bold=bold, bg=bg)
    c = ws4.cell(row=r, column=2, value=v)
    c.font = Font(name="Calibri", size=10, bold=bold, color=fg)
    c.fill = fill(bg); c.border = TB; c.number_format = fmt
    c.alignment = Alignment(horizontal="right", vertical="center")
    for col in range(3, 5):
        ws4.cell(row=r, column=col).fill = fill(bg)
        ws4.cell(row=r, column=col).border = TB
    r += 1

# Line chart
r += 2
chart = LineChart()
chart.title = "Revenue and FCFF — 10-Year Base Case"
chart.style = 10
chart.y_axis.title = "Value ($B)"
chart.x_axis.title = "Year"
chart.width = 20; chart.height = 13

rev_ref  = Reference(ws4, min_col=2, min_row=3, max_col=11, max_row=3)
fcff_ref = Reference(ws4, min_col=2, min_row=9, max_col=11, max_row=9)
from openpyxl.chart.series import SeriesLabel
chart.add_data(rev_ref)
chart.add_data(fcff_ref)
chart.series[0].title = SeriesLabel(v="Revenue ($B)")
chart.series[1].title = SeriesLabel(v="FCFF ($B)")
chart.series[0].graphicalProperties.line.solidFill = MID_BLUE
chart.series[0].graphicalProperties.line.width = 20000
chart.series[1].graphicalProperties.line.solidFill = "375623"
chart.series[1].graphicalProperties.line.width = 20000

ws4.add_chart(chart, f"A{r}")
r += 24
footer(ws4, r, 10)

out = "data/valuations/IBM_review_2026-03-08.xlsx"
wb.save(out)
print(f"Saved: {out}")
